# Generated by Django 4.2.7 on 2023-12-03 11:52

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('description', models.TextField(null=True)),
                ('company', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254, null=True)),
                ('location', models.CharField(max_length=255, null=True, verbose_name='Job Location')),
                ('job_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Remote', 'Remote'), ('Contract', 'Contract'), ('InternShip', 'Internship')], default='Remote', max_length=20)),
                ('work_type', models.CharField(choices=[('On Site', 'Onsite'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], default='On Site', max_length=100)),
                ('education', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Phd', 'Phd')], max_length=30)),
                ('experience', models.CharField(choices=[('No Experience', 'Inexperience'), ('Less than 1 year', 'Less Than A Year'), ('One Year', 'One Year'), ('Two Years', 'Two Years'), ('Two Years and above', 'Above Two Years')], max_length=30)),
                ('salary', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1000000000)])),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('application_link', models.URLField(blank=True)),
                ('positions', models.CharField(max_length=100)),
                ('geo_point', django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('closing_date', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
