# Generated by Django 4.2.7 on 2023-12-02 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='address',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='application_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='location',
            field=models.CharField(max_length=255, null=True, verbose_name='Job Location'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='work_type',
            field=models.CharField(choices=[('On Site', 'Onsite'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], default='On Site', max_length=100),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1000000000)]),
        ),
    ]
