# Generated by Django 4.2.7 on 2023-12-03 19:18

import apps.jobs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='positions',
            field=models.CharField(max_length=100, validators=[apps.jobs.validators.validate_positions]),
        ),
    ]
