# Generated by Django 4.2.7 on 2023-12-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_joblisting_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='positions',
        ),
    ]
