# Generated by Django 4.2.7 on 2023-12-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_joblisting_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='industry',
        ),
    ]
