# Generated by Django 4.2.7 on 2023-12-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_joblisting_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='available_positions',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
