# Generated by Django 4.2.7 on 2023-12-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_joblisting_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
