# Generated by Django 4.2.7 on 2023-12-02 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_joblisting_city_joblisting_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='created',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='updated',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='closing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
