# Generated by Django 4.2.7 on 2023-12-06 20:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_joblisting_available_positions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='salary',
            new_name='max_salary',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='min_salary',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1000000000)]),
        ),
        migrations.CreateModel(
            name='CandidacyApllication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_resume', models.CharField(max_length=120)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobapplication', to='jobs.joblisting')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
