# Generated by Django 4.2.7 on 2023-12-07 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0005_rename_salary_joblisting_max_salary_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidacyApllication',
            new_name='CandidacyApplication',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='responsibility',
            field=models.TextField(null=True),
        ),
    ]
