# Generated by Django 4.2.7 on 2023-12-03 10:09

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_created_joblisting_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='geo_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326),
        ),
    ]
