# Generated by Django 4.2.7 on 2023-12-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_joblisting_geo_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
