# Generated by Django 4.2.7 on 2023-12-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_joblisting_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
