# Generated by Django 4.2.7 on 2023-12-03 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_joblisting_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
